[center]
title="Solar Powered Cars"
description="Solar panels are a marvel of modern engineering. This project explores how their design, manufacturing, and ability to power various vehicles."
src="center.jpg"
alt="Lights"
main_page="main.html"

[[dropdown]]
icon="lightbulb"
label="Applicable Areas"
content="areas.html"

[[dropdown]]
icon="math"
label="Relevant Equations"
content="math.html"

[[dropdown]]
icon="classroom"
label="Key Lesson Points"
content="lessons.html"

[[dropdown]]
icon="globe"
label="Applications in Industry"
content="news.html"
