[center]
title="Light Project"
description="A cool picture of lights that were probably ripped off of the internet. I think they look cool."
src="center.jpg"
alt="Lights"

[[dropdown]]
icon="lightbulb"
label="Key Concepts"
content="concepts.html"

[[dropdown]]
icon="math"
label="Math"
content="math.html"

[[dropdown]]
icon="classroom"
label="Lessons"
content="lessons.html"

[[dropdown]]
icon="newspaper"
label="News"
content="news.html"