[center]
title="Capacitor Spark Demo"
description="Capacitors are an essential component to nearly all the devices you use every day. This demonstration is a great way to grab the attention of an audience and shows the energy storage capability of capacitors."
src="center.gif"
alt="Capacitor Demo"
main_page="main.html"

[[dropdown]]
icon="lightbulb"
label="Applicable Areas"
content="areas.html"

[[dropdown]]
icon="math"
label="Relevant Equations"
content="math.html"

[[dropdown]]
icon="globe"
label="Applications in Industry"
content="industry.html"
